import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import "./typo.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = localFont({
  src: [
    {
      path: '../public/fonts/poppins-regular-webfont.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/poppins-regular-webfont.woff2',
      weight: '700',
      style: 'normal',
    },
    // Add more weights (500, 600, etc.) and italics as needed
  ],
  variable: '--font-poppins', // This creates a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", poppins.variable, "font-sans", geist.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col font-sans"
        suppressHydrationWarning >{children}</body>
    </html>
  );
}
